# Generated by Django 5.0.6 on 2024-06-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('position',), 'verbose_name_plural': 'Product Category'},
        ),
    ]
