# Generated by Django 5.0.6 on 2024-06-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_productcategory_options_product'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('position', 'category'), name='unique_position_per_each_category'),
        ),
    ]
