# Generated by Django 5.0.6 on 2024-06-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_product_unique_position_per_each_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='position',
            field=models.SmallIntegerField(),
        ),
    ]
