# Generated by Django 5.0.6 on 2024-06-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_product_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category', 'position'), 'verbose_name_plural': 'Products'},
        ),
    ]
